name: 262 Commit Checker

on: pull_request

jobs:
   test:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.pull_request.head.sha }} # this is sadly still the merge ref
    - run: git checkout HEAD^2 # to get the actual PR head
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: node scripts/check-commit
